{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceNetworkConnectionFailed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicenetworkconnectionfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceNetworkConnectionFailed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The device could not connect to the network."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceNetworkConnectionFailed"}],"title":"AdaptyError.ErrorCode.cloudServiceNetworkConnectionFailed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:6Adapty0A5ErrorV0B4CodeO35cloudServiceNetworkConnectionFailedyA2EmF","modules":[{"name":"Adapty"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Adapty\/documentation\/Adapty","doc:\/\/org.cocoapods.Adapty\/documentation\/Adapty\/AdaptyError","doc:\/\/org.cocoapods.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum"]]},"references":{"doc://org.cocoapods.Adapty/documentation/Adapty/AdaptyError":{"role":"symbol","title":"AdaptyError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdaptyError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Adapty\/documentation\/Adapty\/AdaptyError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdaptyError"}],"url":"\/documentation\/adapty\/adaptyerror"},"doc://org.cocoapods.Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum/cloudServiceNetworkConnectionFailed":{"role":"symbol","title":"AdaptyError.ErrorCode.cloudServiceNetworkConnectionFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceNetworkConnectionFailed"}],"abstract":[{"type":"text","text":"The device could not connect to the network."}],"identifier":"doc:\/\/org.cocoapods.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceNetworkConnectionFailed","kind":"symbol","type":"topic","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicenetworkconnectionfailed"},"doc://org.cocoapods.Adapty/documentation/Adapty":{"role":"collection","title":"Adapty","abstract":[],"identifier":"doc:\/\/org.cocoapods.Adapty\/documentation\/Adapty","kind":"symbol","type":"topic","url":"\/documentation\/adapty"},"doc://org.cocoapods.Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum":{"role":"symbol","title":"AdaptyError.ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum"}}}