{"abstract":[{"text":"The device could not connect to the network.","type":"text"}],"metadata":{"symbolKind":"case","externalID":"s:6Adapty0A5ErrorV0B4CodeO35cloudServiceNetworkConnectionFailedyA2EmF","title":"AdaptyError.ErrorCode.cloudServiceNetworkConnectionFailed","modules":[{"name":"Adapty"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cloudServiceNetworkConnectionFailed","kind":"identifier"}],"role":"symbol","roleHeading":"Case"},"variants":[{"paths":["\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicenetworkconnectionfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/ios-sdk.Adapty\/documentation\/Adapty","doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError","doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum"]]},"identifier":{"url":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceNetworkConnectionFailed","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cloudServiceNetworkConnectionFailed"}],"languages":["swift"]}]}],"references":{"doc://ios-sdk.Adapty/documentation/Adapty":{"title":"Adapty","role":"collection","url":"\/documentation\/adapty","type":"topic","kind":"symbol","identifier":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty","abstract":[]},"doc://ios-sdk.Adapty/documentation/Adapty/AdaptyError":{"url":"\/documentation\/adapty\/adaptyerror","type":"topic","kind":"symbol","role":"symbol","title":"AdaptyError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdaptyError"}],"identifier":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError","navigatorTitle":[{"kind":"identifier","text":"AdaptyError"}],"abstract":[]},"doc://ios-sdk.Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum":{"identifier":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"type":"topic","title":"AdaptyError.ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}]},"doc://ios-sdk.Adapty/documentation/Adapty/AdaptyError/ErrorCode-swift.enum/cloudServiceNetworkConnectionFailed":{"identifier":"doc:\/\/ios-sdk.Adapty\/documentation\/Adapty\/AdaptyError\/ErrorCode-swift.enum\/cloudServiceNetworkConnectionFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudServiceNetworkConnectionFailed"}],"kind":"symbol","url":"\/documentation\/adapty\/adaptyerror\/errorcode-swift.enum\/cloudservicenetworkconnectionfailed","type":"topic","abstract":[{"text":"The device could not connect to the network.","type":"text"}],"title":"AdaptyError.ErrorCode.cloudServiceNetworkConnectionFailed","role":"symbol"}}}